produit_index:
    path:     /
    defaults: { _controller: "ProduitBundle:Produit:index" }
    methods:  GET

produit_show:
    path:     /{idProduit}/show
    defaults: { _controller: "ProduitBundle:Produit:show" }
    methods:  GET

produit_new:
    path:     /new
    defaults: { _controller: "ProduitBundle:Produit:new" }
    methods:  [GET, POST]

produit_edit:
    path:     /{idProduit}/edit
    defaults: { _controller: "ProduitBundle:Produit:edit" }
    methods:  [GET, POST]

produit_delete:
    path:     /{idProduit}/delete
    defaults: { _controller: "ProduitBundle:Produit:delete" }
    methods:  DELETE
