<?php

namespace EventBundle\Repository;

/**
 * CategorieEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieEventRepository extends \Doctrine\ORM\EntityRepository
{
}
